### ISSUE TITLE
FullSubNet-plus

### ISSUE THREAD

**Issue by MariasStory** [PINTO0309/PINTO_model_zoo#187]
### Issue Type

Feature Request

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

TensorFlow.js

### Model name and Weights/Checkpoints URL

https://github.com/hit-thusz-RookieCJ/FullSubNet-plus

### Description

Can be added to "12. Sound Classifier"

**Comment by PINTO0309** [comment]
The sound transformation model depends on the audio length, but how would you like the input width to be fixed? ONNX with a variable input width will cause an error in **`Reshape`** operation and cannot be used.

```
Shapes:
    noisy_mag: [B, 1, F, T]
    noisy_real: [B, 1, F, T]
    noisy_imag: [B, 1, F, T]
    return: [B, 2, F, T]
```
For example:
```
A100VV1V2XDQI7_2minstimittext_enrol_speech_mobile--208ffcae-d8d3-4557-a09b-d9d5a852cd42--10603.wav
noisy_mag: torch.Size([1, 1, 257, 7508])
noisy_real: torch.Size([1, 1, 257, 7508])
noisy_imag: torch.Size([1, 1, 257, 7508])

A12FTSX85NQ8N9_2minstimittext_enrol_speech_mobile--47a655cc-273f-495e-a031-90b490263470--45527.wav
noisy_mag: torch.Size([1, 1, 257, 1276])
noisy_real: torch.Size([1, 1, 257, 1276])
noisy_imag: torch.Size([1, 1, 257, 1276])
```
